"""
Script to seed the database with football trivia questions.
Run this script once to populate the questions table.
"""

import asyncio
from sqlalchemy import insert

from .db import engine, Base, Question, async_session_maker


SAMPLE_QUESTIONS = [
    {
        "question_text": "Which club did Lionel Messi join in 2023?",
        "option_a": "Inter Miami",
        "option_b": "PSG",
        "option_c": "Barcelona",
        "option_d": "Chelsea",
        "correct_answer": "A",
        "difficulty": "medium",
        "category": "Transfers",
    },
    {
        "question_text": "Who won the UEFA Euro 2016?",
        "option_a": "France",
        "option_b": "Portugal",
        "option_c": "Germany",
        "option_d": "Spain",
        "correct_answer": "B",
        "difficulty": "medium",
        "category": "Euro Cup",
    },
    {
        "question_text": "Which country hosted the FIFA World Cup 2010?",
        "option_a": "Brazil",
        "option_b": "South Africa",
        "option_c": "Germany",
        "option_d": "Russia",
        "correct_answer": "B",
        "difficulty": "easy",
        "category": "World Cup",
    },
    {
        "question_text": "Which player is known as 'El Fenómeno'?",
        "option_a": "Ronaldo Nazário",
        "option_b": "Ronaldinho",
        "option_c": "Neymar",
        "option_d": "Romário",
        "correct_answer": "A",
        "difficulty": "medium",
        "category": "Players",
    },
    {
        "question_text": "Which team won the Premier League 2016 when Leicester City shocked the world?",
        "option_a": "Leicester City",
        "option_b": "Arsenal",
        "option_c": "Chelsea",
        "option_d": "Manchester United",
        "correct_answer": "A",
        "difficulty": "easy",
        "category": "Premier League",
    },
    {
        "question_text": "Who won the Golden Boot at the 2018 World Cup?",
        "option_a": "Harry Kane",
        "option_b": "Mbappé",
        "option_c": "Griezmann",
        "option_d": "Cavani",
        "correct_answer": "A",
        "difficulty": "medium",
        "category": "World Cup",
    },
    {
        "question_text": "Which club has the nickname 'The Blues'?",
        "option_a": "Chelsea",
        "option_b": "Manchester City",
        "option_c": "Napoli",
        "option_d": "Everton",
        "correct_answer": "A",
        "difficulty": "easy",
        "category": "Clubs",
    },
    {
        "question_text": "How many Champions League titles has Real Madrid won?",
        "option_a": "10",
        "option_b": "12",
        "option_c": "14",
        "option_d": "15",
        "correct_answer": "C",
        "difficulty": "hard",
        "category": "Champions League",
    },
    {
        "question_text": "Who is the all-time top scorer of FC Barcelona?",
        "option_a": "Suárez",
        "option_b": "Messi",
        "option_c": "Romário",
        "option_d": "Rivaldo",
        "correct_answer": "B",
        "difficulty": "easy",
        "category": "Players",
    },
    {
        "question_text": "Which country won the Copa América 2021?",
        "option_a": "Argentina",
        "option_b": "Brazil",
        "option_c": "Chile",
        "option_d": "Uruguay",
        "correct_answer": "A",
        "difficulty": "easy",
        "category": "Copa America",
    },
    {
        "question_text": "Which club did Haaland join in 2022?",
        "option_a": "Borussia Dortmund",
        "option_b": "Manchester City",
        "option_c": "RB Salzburg",
        "option_d": "Real Madrid",
        "correct_answer": "B",
        "difficulty": "easy",
        "category": "Transfers",
    },
    {
        "question_text": "Which coach won the Champions League with Porto in 2004?",
        "option_a": "Alex Ferguson",
        "option_b": "José Mourinho",
        "option_c": "Pep Guardiola",
        "option_d": "Carlo Ancelotti",
        "correct_answer": "B",
        "difficulty": "medium",
        "category": "Coaches",
    },
    {
        "question_text": "Which country has hosted the most FIFA World Cups?",
        "option_a": "Mexico",
        "option_b": "Italy",
        "option_c": "Brazil",
        "option_d": "France",
        "correct_answer": "A",
        "difficulty": "medium",
        "category": "World Cup",
    },
    {
        "question_text": "Which team plays at Old Trafford?",
        "option_a": "Manchester United",
        "option_b": "Manchester City",
        "option_c": "Liverpool",
        "option_d": "Everton",
        "correct_answer": "A",
        "difficulty": "easy",
        "category": "Stadiums",
    },
    {
        "question_text": "What is the minimum number of players required to start a football match?",
        "option_a": "6",
        "option_b": "7",
        "option_c": "8",
        "option_d": "9",
        "correct_answer": "B",
        "difficulty": "hard",
        "category": "Rules",
    },
    {
        "question_text": "Which nation won the first-ever UEFA Euro championship?",
        "option_a": "Spain",
        "option_b": "Soviet Union",
        "option_c": "Germany",
        "option_d": "Hungary",
        "correct_answer": "B",
        "difficulty": "hard",
        "category": "Euro Cup",
    },
    {
        "question_text": "Who is known as 'The Egyptian King'?",
        "option_a": "Mohamed Salah",
        "option_b": "Mahrez",
        "option_c": "Hakimi",
        "option_d": "Trezeguet",
        "correct_answer": "A",
        "difficulty": "easy",
        "category": "Players",
    },
    {
        "question_text": "Who scored the fastest hat-trick in Premier League history?",
        "option_a": "Sadio Mané",
        "option_b": "Aguero",
        "option_c": "Rooney",
        "option_d": "Henry",
        "correct_answer": "A",
        "difficulty": "hard",
        "category": "Premier League",
    },
    {
        "question_text": "Which club is known as 'The Gunners'?",
        "option_a": "Chelsea",
        "option_b": "Arsenal",
        "option_c": "Tottenham",
        "option_d": "Liverpool",
        "correct_answer": "B",
        "difficulty": "easy",
        "category": "Premier League",
    },
    {
        "question_text": "Who won the Ballon d'Or in 2010?",
        "option_a": "Messi",
        "option_b": "Xavi",
        "option_c": "Iniesta",
        "option_d": "Ronaldo",
        "correct_answer": "A",
        "difficulty": "medium",
        "category": "Awards",
    },
    {
        "question_text": "Which country won the 2006 FIFA World Cup?",
        "option_a": "France",
        "option_b": "Italy",
        "option_c": "Germany",
        "option_d": "Portugal",
        "correct_answer": "B",
        "difficulty": "medium",
        "category": "World Cup",
    },
    {
        "question_text": "Which club has won the most Europa League titles?",
        "option_a": "Atletico Madrid",
        "option_b": "Liverpool",
        "option_c": "Sevilla",
        "option_d": "Valencia",
        "correct_answer": "C",
        "difficulty": "hard",
        "category": "Europa League",
    },
    {
        "question_text": "Which player is known for the 'Panenka' penalty?",
        "option_a": "Antonín Panenka",
        "option_b": "Pirlo",
        "option_c": "Zidane",
        "option_d": "Kaká",
        "correct_answer": "A",
        "difficulty": "medium",
        "category": "History",
    },
    {
        "question_text": "Which club did Zlatan Ibrahimović NOT play for?",
        "option_a": "Juventus",
        "option_b": "AC Milan",
        "option_c": "Barcelona",
        "option_d": "Liverpool",
        "correct_answer": "D",
        "difficulty": "easy",
        "category": "Players",
    },
    {
        "question_text": "Which team has won the AFCON (Africa Cup of Nations) the most times?",
        "option_a": "Nigeria",
        "option_b": "Cameroon",
        "option_c": "Egypt",
        "option_d": "Ghana",
        "correct_answer": "C",
        "difficulty": "medium",
        "category": "AFCON",
    },
    {
        "question_text": "Which goalkeeper has the most clean sheets in Premier League history?",
        "option_a": "Van der Sar",
        "option_b": "Petr Čech",
        "option_c": "Alisson",
        "option_d": "Schmeichel",
        "correct_answer": "B",
        "difficulty": "hard",
        "category": "Premier League",
    },

    # 25 more below
    {
        "question_text": "Which team won the UEFA Champions League in 2019?",
        "option_a": "Liverpool",
        "option_b": "Tottenham",
        "option_c": "Real Madrid",
        "option_d": "Barcelona",
        "correct_answer": "A",
        "difficulty": "easy",
        "category": "Champions League",
    },
    {
        "question_text": "Which player is famous for the 'Hand of God' goal?",
        "option_a": "Maradona",
        "option_b": "Pelé",
        "option_c": "Messi",
        "option_d": "Zidane",
        "correct_answer": "A",
        "difficulty": "medium",
        "category": "History",
    },
    {
        "question_text": "Which club has the nickname 'The Citizens'?",
        "option_a": "Liverpool",
        "option_b": "Manchester City",
        "option_c": "Chelsea",
        "option_d": "Arsenal",
        "correct_answer": "B",
        "difficulty": "easy",
        "category": "Premier League",
    },
    {
        "question_text": "Which player has the most assists in Premier League history?",
        "option_a": "Lampard",
        "option_b": "Giggs",
        "option_c": "De Bruyne",
        "option_d": "Fabregas",
        "correct_answer": "B",
        "difficulty": "hard",
        "category": "Premier League",
    },
    {
        "question_text": "Who won the FIFA Puskás Award in 2020?",
        "option_a": "Son Heung-min",
        "option_b": "Lewandowski",
        "option_c": "Ronaldo",
        "option_d": "Zlatan",
        "correct_answer": "A",
        "difficulty": "medium",
        "category": "Awards",
    },
    {
        "question_text": "Which country has won the most UEFA Euro titles?",
        "option_a": "Germany",
        "option_b": "Spain",
        "option_c": "Italy",
        "option_d": "Portugal",
        "correct_answer": "A",
        "difficulty": "hard",
        "category": "Euro Cup",
    },
    {
        "question_text": "Which manager is known as 'The Professor'?",
        "option_a": "Arsène Wenger",
        "option_b": "Guardiola",
        "option_c": "Klopp",
        "option_d": "Sarri",
        "correct_answer": "A",
        "difficulty": "medium",
        "category": "Coaches",
    },
    {
        "question_text": "Which country won the 1998 World Cup?",
        "option_a": "France",
        "option_b": "Brazil",
        "option_c": "Germany",
        "option_d": "Argentina",
        "correct_answer": "A",
        "difficulty": "easy",
        "category": "World Cup",
    },
    {
        "question_text": "How long is a penalty shootout kick distance?",
        "option_a": "10 yards",
        "option_b": "12 yards",
        "option_c": "15 yards",
        "option_d": "18 yards",
        "correct_answer": "B",
        "difficulty": "easy",
        "category": "Rules",
    },
    {
        "question_text": "Which club did Cristiano Ronaldo join in 2023?",
        "option_a": "Al Nassr",
        "option_b": "Sporting CP",
        "option_c": "Juventus",
        "option_d": "Miami FC",
        "correct_answer": "A",
        "difficulty": "easy",
        "category": "Transfers",
    },
    {
        "question_text": "Which country won the Olympic gold medal in football 2021?",
        "option_a": "Spain",
        "option_b": "Brazil",
        "option_c": "Argentina",
        "option_d": "Japan",
        "correct_answer": "B",
        "difficulty": "medium",
        "category": "Olympics",
    },
    {
        "question_text": "Which stadium is home to Bayern Munich?",
        "option_a": "Allianz Arena",
        "option_b": "Signal Iduna Park",
        "option_c": "Camp Nou",
        "option_d": "Bernabéu",
        "correct_answer": "A",
        "difficulty": "easy",
        "category": "Stadiums",
    },
    {
        "question_text": "Which country has produced the most Ballon d'Or winners?",
        "option_a": "France",
        "option_b": "Brazil",
        "option_c": "Argentina",
        "option_d": "Germany",
        "correct_answer": "B",
        "difficulty": "hard",
        "category": "Awards",
    },
    {
        "question_text": "Who is AC Milan's all-time top scorer?",
        "option_a": "Shevchenko",
        "option_b": "Inzaghi",
        "option_c": "Kaká",
        "option_d": "Ibrahimović",
        "correct_answer": "A",
        "difficulty": "hard",
        "category": "Players",
    },
    {
        "question_text": "Which team won La Liga 2021?",
        "option_a": "Barcelona",
        "option_b": "Real Madrid",
        "option_c": "Atletico Madrid",
        "option_d": "Sevilla",
        "correct_answer": "C",
        "difficulty": "medium",
        "category": "La Liga",
    },
    {
        "question_text": "Who scored the winning goal in the 2010 World Cup final?",
        "option_a": "Iniesta",
        "option_b": "Villa",
        "option_c": "Schneider",
        "option_d": "Robben",
        "correct_answer": "A",
        "difficulty": "medium",
        "category": "World Cup",
    },
    {
        "question_text": "Which player has the most UEFA Champions League titles?",
        "option_a": "Gento",
        "option_b": "Ronaldo",
        "option_c": "Messi",
        "option_d": "Maldini",
        "correct_answer": "A",
        "difficulty": "hard",
        "category": "Champions League",
    },
    {
        "question_text": "Which club is known as 'BVB'?",
        "option_a": "Bayern Munich",
        "option_b": "Borussia Dortmund",
        "option_c": "Bayer Leverkusen",
        "option_d": "RB Leipzig",
        "correct_answer": "B",
        "difficulty": "easy",
        "category": "Bundesliga",
    },
    {
        "question_text": "Which team won Serie A in 2020?",
        "option_a": "Juventus",
        "option_b": "Inter Milan",
        "option_c": "AC Milan",
        "option_d": "Napoli",
        "correct_answer": "B",
        "difficulty": "medium",
        "category": "Serie A",
    },
    {
        "question_text": "Which team did Kylian Mbappé join in 2017?",
        "option_a": "PSG",
        "option_b": "Monaco",
        "option_c": "Real Madrid",
        "option_d": "Lyon",
        "correct_answer": "A",
        "difficulty": "easy",
        "category": "Transfers",
    },
    {
        "question_text": "Who is the youngest goalscorer in World Cup history?",
        "option_a": "Pelé",
        "option_b": "Mbappé",
        "option_c": "Messi",
        "option_d": "Owen",
        "correct_answer": "A",
        "difficulty": "hard",
        "category": "World Cup",
    },
    {
        "question_text": "Which team won the FA Cup 2020?",
        "option_a": "Chelsea",
        "option_b": "Arsenal",
        "option_c": "Manchester United",
        "option_d": "Leicester City",
        "correct_answer": "B",
        "difficulty": "medium",
        "category": "FA Cup",
    },
    {
        "question_text": "Which country has the nickname 'La Roja'?",
        "option_a": "Spain",
        "option_b": "Chile",
        "option_c": "Portugal",
        "option_d": "Mexico",
        "correct_answer": "A",
        "difficulty": "easy",
        "category": "National Teams",
    },
    {
        "question_text": "Who won the 2014 Ballon d'Or?",
        "option_a": "Messi",
        "option_b": "Ronaldo",
        "option_c": "Neuer",
        "option_d": "Robben",
        "correct_answer": "B",
        "difficulty": "medium",
        "category": "Awards",
    },
    {
        "question_text": "Which club has won Ligue 1 the most times?",
        "option_a": "PSG",
        "option_b": "Marseille",
        "option_c": "Saint-Étienne",
        "option_d": "Lyon",
        "correct_answer": "C",
        "difficulty": "hard",
        "category": "Ligue 1",
    },
    
]



async def seed_questions():
    """Seed the database with sample questions."""
    async with engine.begin() as conn:
        await conn.run_sync(Base.metadata.create_all)

    async with async_session_maker() as session:
        try:
            # Check if questions already exist
            from sqlalchemy import select
            result = await session.execute(select(Question))
            existing_questions = result.scalars().all()

            if len(existing_questions) > 0:
                print(f"Database already contains {len(existing_questions)} questions. Skipping seeding.")
                return

            # Insert sample questions
            for question_data in SAMPLE_QUESTIONS:
                question = Question(**question_data)
                session.add(question)

            await session.commit()
            print(f"Successfully seeded {len(SAMPLE_QUESTIONS)} questions!")

        except Exception as e:
            print(f"Error seeding database: {e}")
            await session.rollback()
            raise


if __name__ == "__main__":
    asyncio.run(seed_questions())
